name: CI (Disabled)

# CI tests are temporarily disabled
# Will be reimplemented in a future task

on:
  # Empty to prevent this workflow from running
  # Original triggers were:
  # push:
  #   branches: [ master ]
  # pull_request:
  #   branches: [ master ]

jobs:
  placeholder:
    runs-on: ubuntu-latest
    steps:
      - name: CI tests disabled
        run: echo "CI tests are temporarily disabled and will be reimplemented in the future."